# Generated by Django 5.0.1 on 2024-01-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Title',
            new_name='Tittle',
        ),
    ]
