# Generated by Django 5.0.1 on 2024-01-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_title_menu_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Tittle',
            new_name='Title',
        ),
    ]
